### ISSUE TITLE
Odroid-GO support

### ISSUE THREAD

**Issue by mad-ady** [botofancalin/M5Stack-MultiApp-Advanced#10]
I've tested a slightly older build of your app (great work, by the way!) on an Odroid GO (https://www.hardkernel.com/main/products/prdt_info.php?g_code=G152875062626). I got the prebuilt image from here: https://forum.odroid.com/viewtopic.php?t=31705&p=229847

It mostly works, but button mapping is not ideal, and I had issues with web radio (I could hear static instead of the stream).

If you want to have a look and lack the hardware I could ask for Hardkernel to kindly donate a unit.

Cheers!

**Comment by botofancalin** [comment]
I don't have the Odroid Go hardware.  I will try to remap the keys from code to make it compatible with that hardware.  I already added support for ESP-Wrover-Kit. See the platformio.ini for details.

I recommend compiling the firmware on PlatformIO instead using precompiled version.

You get no audio output because the Odroid Go got it all wrong with the PAM8304A audio amplifier they use. 

![o-go amp](https://user-images.githubusercontent.com/32721615/44616796-29b6b780-a85f-11e8-9d5b-b8175ed78850.PNG)

![amp usage](https://user-images.githubusercontent.com/32721615/44616821-b6617580-a85f-11e8-8172-b6cbad907309.PNG)


They connected the DAC channels outputs to diferential input of amplifier. Beside, they connected the ON/OFF pin of the amplifier to the GPIO25. That's one of the DAC output...

C2 should be connected to IO25 and C16 should be connected to GND. If they want to turn the amp on/off from code, /SD should be connected to some other GPIO. The volume can be set by scaling the audio samples from code.

Anyway... i could make some code tweaks to make it work... but will be nice to be able to test it on actual hardware.

**Comment by mad-ady** [comment]
I've been meaning to ask - do you think you can support Odroid-Go as well,
or is it too different of a platform or has other challenges (regarding
DAC, etc)? I was thinking of a different branch or release that could work
with GO.

**Comment by botofancalin** [comment]
I started adapting the multiapp to Odroid Go on this on this repository: https://github.com/botofancalin/Odroid-Go-MultiApp
The implemented apps are working fine.
I implemented the code that fix the DAC connection issue on GO. 
So the webradio work's fine now. 
Still there is a problem with GPIO's 4 and 15. They can't be used as Oscilloscope input if the Wifi is ON. Turn the wifi OFF and the oscilloscope will work fine too ;)

There are still lots to do on this project. Including GUI modifications.
If i will find enough time, i chould add this whole firmware code to official GO firmware. So user can chose between my apps and game emulators.
There is enough space on GO flash to do that.

**Comment by mad-ady** [comment]
Sounds great! Regarding launcher - the launcher used for games is closed
source despite community requests, but the emulators are open-source. But
you can package it as a fw and flash it on demand - at least until a new
open launcher is released.
Can you point me to building instructions?

**Comment by botofancalin** [comment]
I was talking about this firmware: https://github.com/OtherCrashOverride/odroid-go-firmware
I added the build and flash instructions on the repository readme: https://github.com/botofancalin/Odroid-Go-MultiApp
